AWSTemplateFormatVersion: "2010-09-09"
Description: "lenders-library - bucket, bucket policy, cloudfront, OAI, & associated DNS entry"
Parameters:
  HostedZoneId:
    Type: String
    Description: The Id of an Amazon Route 53 hosted zone to create the alias in.
    ConstraintDescription: must be a valid DNS zone name.
  HostedZoneDomain:
    Type: String
    Description: The DNS name for the root of the hostedzone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  WebsiteContent:
    Type: AWS::S3::Bucket
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${WebsiteContent} OAI"
  ReadPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebsiteContent
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${WebsiteContent}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        # Aliases:
        #   - !Sub "ll.${HostedZoneDomain}"
        #   - !Sub "www.ll.${HostedZoneDomain}"
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref AcmCertificateArn
        #   MinimumProtocolVersion: "TLSv1.2_2018"
        #   SslSupportMethod: "sni-only"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: s3origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: s3origin
            DomainName: !GetAtt "WebsiteContent.DomainName"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
  DomainDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: HostedZoneId
      RecordSets:
        - Name: !Sub "ll.${HostedZoneDomain}"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt WebsiteCDN.DomainName
        - Name: !Sub "www.ll.${HostedZoneDomain}"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt WebsiteCDN.DomainName
Outputs:
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref WebsiteContent
  DistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref WebsiteCDN
  Domain:
    Description: "Cloudfront Domain"
    Value: !GetAtt WebsiteCDN.DomainName
